import express from "express";
import dotenv from "dotenv";
dotenv.config();
import morgan from "morgan";
import cookieParser from "cookie-parser";
import connectDB from "./db/db.js";
import { userRouter } from "./routes/user.routes.js";
import { projectRouter } from "./routes/project.routes.js";
import { redisConnect } from "./services/redis.service.js";
import cors from "cors";
connectDB();
redisConnect();
const app = express();
const allowedOrigins = ["http://localhost:5173"];
app.use(morgan("dev"));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(cors());
app.use("/users", userRouter);
app.use("/projects", projectRouter);

export default app;
